# Generated by Django 3.1.2 on 2021-07-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrdName', models.CharField(blank=True, default='', max_length=60)),
                ('Gstid', models.CharField(blank=True, default='', max_length=60)),
                ('Addr1', models.CharField(blank=True, default='', max_length=60)),
                ('Addr2', models.CharField(blank=True, default='', max_length=60)),
                ('Place', models.CharField(blank=True, default='', max_length=60)),
                ('Pincode', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, default='', max_length=60)),
                ('QtyUnit', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='loginn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, default='', max_length=60)),
                ('lname', models.CharField(blank=True, default='', max_length=60)),
                ('email', models.EmailField(default='', max_length=60, unique=True)),
                ('pwd', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='itmcustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxableAmount', models.FloatField(default=0)),
                ('Quantity', models.FloatField(default=0)),
                ('ProducctDesc', models.CharField(blank=True, default='', max_length=60)),
                ('cid', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.customer')),
                ('pid', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.items')),
            ],
        ),
    ]
