# Generated by Django 3.1.2 on 2021-07-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxableAmount', models.FloatField(default=0)),
                ('Quantity', models.FloatField(default=0)),
                ('OtherValue', models.FloatField(blank=True, default='')),
                ('VehicleNo', models.CharField(blank=True, default='', max_length=60)),
                ('VehicleType', models.CharField(blank=True, default='', max_length=60)),
                ('iid', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.itmcustomer')),
            ],
        ),
    ]
