# Generated by Django 3.1.2 on 2021-07-01 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cid',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.customer'),
        ),
    ]
