# Generated by Django 3.1.2 on 2021-07-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_order_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='ProductName',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
